name: PHP Linting

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.4", "8.1", "8.2"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, phpcs

      - name: Install WordPress Coding Standards
        run: |
          composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Run PHP_CodeSniffer
        run: phpcs --standard=WordPress --extensions=php $GITHUB_WORKSPACE
