name: Release Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build Release
        run: |
          zip -r custom-file-organizer-${GITHUB_REF#refs/tags/}.zip . -x "*.git*"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.2.0
        with:
          name: custom-file-organizer
          path: custom-file-organizer-${GITHUB_REF#refs/tags/}.zip
